"""Infrastructure approval: move the release anchor to a reviewed commit.

The anchor /opt/car-agent/shared/release-infrastructure.json binds the host to one reviewed
commit's deploy/cloud/** (aggregate of per-file blob digests) and records which of those files
are installed where. A deploy only reads it (deploy/cloud/README.md). Approving a commit
installs its changed files and rewrites the anchor, as root, under the release transaction
lock, with a backup and an automatic restore on failure.

Eight approvals (2026-09-06..09-28) were generated by session-local scripts that lived only
under .artifacts/infrastructure-approval/; this module replaces them. The three root scripts
below are those scripts with their constants turned into placeholders.

- prepare_approval(): reads the installed anchor, builds the candidate from committed blobs of
  the target commit (REQUIRED_INSTALLED is read from that commit too), renders the materials
  into <artifact_root>/<sha>/ and runs the anchor validator locally. Changes nothing remotely.
- apply_approval(): re-reads the anchor (it must be the one the materials were built against),
  stages the materials through prepare-upload + scp, runs the digest-pinned root entry over
  `ssh sudo -n bash -s` and reads the anchor back.
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
import secrets
import subprocess
import sys
from collections.abc import Mapping
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from scripts.cloud_release_lib import (
    CommandRunner,
    ReleaseRequest,
    _git,
    _git_blob,
    compute_infrastructure_digest,
    require_clean_main_commit,
)

ANCHOR_PATH = "/opt/car-agent/shared/release-infrastructure.json"
APPROVALS_ROOT = "/opt/car-agent/shared/evidence/infrastructure-approvals"
INCOMING_ROOT = "/opt/car-agent/incoming/releases"
LOCK_HELPER = "deploy/cloud/transaction-lock.sh"
CONFIG_SUFFIXES = (".json", ".yaml", ".mjs", ".service", ".timer")
APPLY = "apply-infrastructure-approval.sh"
ANCHOR = "release-infrastructure.json"
WRAPPER = "root-snapshot-wrapper.sh"
ENTRY = "trusted-root-entry.sh"
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
NONCE_RE = re.compile(r"^[0-9a-f]{32}$")
ANCHOR_KEYS = frozenset({"schema_version", "infrastructure_sha256", "source_files", "installed_files"})


class ApprovalError(RuntimeError):
    """An approval step refused or failed; the message says how far it got."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _canonical(source_files: Mapping[str, str]) -> bytes:
    return json.dumps(source_files, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ApprovalError("anchor has a duplicate key")
        result[key] = value
    return result


def parse_anchor(data: bytes) -> dict[str, Any]:
    try:
        payload = json.loads(data.decode("utf-8"), object_pairs_hook=_strict_object)
    except (UnicodeDecodeError, ValueError) as exc:
        raise ApprovalError("anchor is not valid JSON") from exc
    if not isinstance(payload, dict) or set(payload) != ANCHOR_KEYS or payload["schema_version"] != 1:
        raise ApprovalError("anchor shape is invalid")
    sources = payload["source_files"]
    if not isinstance(sources, dict) or any(
        not isinstance(value, str) or not SHA256_RE.fullmatch(value) for value in sources.values()
    ):
        raise ApprovalError("anchor source digests are invalid")
    if _sha256(_canonical(sources)) != payload["infrastructure_sha256"]:
        raise ApprovalError("anchor aggregate does not match its source digests")
    rows = payload["installed_files"]
    if not isinstance(rows, list) or any(
        not isinstance(row, dict) or set(row) != {"source_path", "target_path", "sha256"} for row in rows
    ):
        raise ApprovalError("anchor installed files are invalid")
    return payload


def read_anchor(request: ReleaseRequest, runner: CommandRunner) -> tuple[bytes, dict[str, Any]]:
    result = runner.run(
        request.ssh.ssh_argv(f"sudo -n cat {ANCHOR_PATH}"), cwd=request.repo, check=False, timeout_s=60
    )
    if result.returncode != 0:
        raise ApprovalError("could not read the installed infrastructure anchor")
    data = result.stdout.encode("utf-8")
    return data, parse_anchor(data)


# ---------------------------------------------------------------- candidate


def required_installed_at(repo: Path, sha: str) -> dict[str, str]:
    """REQUIRED_INSTALLED as committed in the target's remote preflight, not the working tree's."""
    text = _git_blob(repo, sha, "scripts/cloud_release_lib.py").decode("utf-8")
    match = re.search(r"^REQUIRED_INSTALLED = (\{.*?^\})", text, re.M | re.S)
    if match is None:
        raise ApprovalError("the target commit declares no REQUIRED_INSTALLED")
    required = ast.literal_eval(match.group(1))
    if not isinstance(required, dict) or any(
        not isinstance(source, str) or not source.startswith("deploy/cloud/")
        or not isinstance(target, str) or not target.startswith("/")
        for source, target in required.items()
    ):
        raise ApprovalError("REQUIRED_INSTALLED in the target commit is invalid")
    return required


@dataclass(frozen=True)
class Install:
    name: str
    source: str
    target: str
    mode: str
    new: str
    old: str  # "-" for a file the anchor did not install before


@dataclass(frozen=True)
class Candidate:
    target_sha: str
    aggregate: str
    source_files: dict[str, str]
    required: dict[str, str]
    anchor_bytes: bytes
    installs: tuple[Install, ...]
    blobs: dict[str, bytes]
    changed_sources: tuple[str, ...]


def build_candidate(repo: Path, target_sha: str, previous: Mapping[str, Any]) -> Candidate:
    listing = _git(repo, "ls-tree", "-r", "--name-only", target_sha, "--", "deploy/cloud").stdout.splitlines()
    paths = sorted(path for path in listing if path and path != "deploy/cloud/README.md")
    blobs = {path: _git_blob(repo, target_sha, path) for path in paths}
    sources = {path: _sha256(blobs[path]) for path in paths}
    aggregate = _sha256(_canonical(sources))
    if aggregate != compute_infrastructure_digest(repo, target_sha):
        raise ApprovalError("candidate aggregate disagrees with the release gate")
    required = required_installed_at(repo, target_sha)
    if set(required) - set(sources):
        raise ApprovalError("REQUIRED_INSTALLED names files outside deploy/cloud: "
                            + ", ".join(sorted(set(required) - set(sources))))
    previous_target = {row["source_path"]: row["target_path"] for row in previous["installed_files"]}
    previous_digest = {row["source_path"]: row["sha256"] for row in previous["installed_files"]}
    if set(previous_target) - set(required):
        raise ApprovalError("removing installed files is not supported: "
                            + ", ".join(sorted(set(previous_target) - set(required))))
    moved = sorted(source for source in required if previous_target.get(source, required[source]) != required[source])
    if moved:
        raise ApprovalError("moving installed files is not supported: " + ", ".join(moved))
    if LOCK_HELPER not in previous_digest or sources.get(LOCK_HELPER) != previous_digest[LOCK_HELPER]:
        raise ApprovalError("transaction-lock.sh must be installed and unchanged: the approval sources it")
    installs = []
    for source, target in required.items():
        if previous_digest.get(source) == sources[source]:
            continue
        name = source.rsplit("/", 1)[1]
        installs.append(Install(
            name=name,
            source=source,
            target=target,
            mode="0644" if name.endswith(CONFIG_SUFFIXES) else "0755",
            new=sources[source],
            old=previous_digest.get(source, "-"),
        ))
    names = [item.name for item in installs]
    if len(set(names)) != len(names) or set(names) & {APPLY, ANCHOR, WRAPPER, ENTRY}:
        raise ApprovalError("installed file names collide in the upload directory")
    anchor = {
        "infrastructure_sha256": aggregate,
        "installed_files": [
            {"sha256": sources[source], "source_path": source, "target_path": target}
            for source, target in required.items()
        ],
        "schema_version": 1,
        "source_files": sources,
    }
    before = previous["source_files"]
    return Candidate(
        target_sha=target_sha,
        aggregate=aggregate,
        source_files=sources,
        required=required,
        anchor_bytes=(json.dumps(anchor, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
        installs=tuple(installs),
        blobs={item.name: blobs[item.source] for item in installs},
        changed_sources=tuple(sorted(p for p in set(sources) | set(before) if before.get(p) != sources.get(p))),
    )


# ---------------------------------------------------------------- root scripts

APPLY_TEMPLATE = r'''#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

# 基础设施批准：装入目标提交变更的已安装文件，并改写批准锚（由 scripts/cloud_infra_approval.py 生成）。
# 验旧锚 → 持发布锁 → 备份 → 装新 → 验新锚；任一步失败自动还原。

readonly TARGET_SHA="@@TARGET@@"
readonly TARGET_INFRASTRUCTURE_SHA256="@@AGGREGATE@@"
readonly PREVIOUS_INFRASTRUCTURE_SHA256="@@PREV_AGGREGATE@@"
readonly CANDIDATE_MANIFEST_SHA256="@@MANIFEST@@"
readonly TRANSACTION_LOCK_SHA256="@@LOCK_SHA@@"
readonly SHARED_ROOT="/opt/car-agent/shared"
readonly SCRIPT_ROOT="${SHARED_ROOT}/bin"
readonly INPUT_ROOT="@@SNAPSHOT@@"
readonly BACKUP="@@BACKUP@@"
readonly ANCHOR_TARGET="${SHARED_ROOT}/release-infrastructure.json"
# name|target|mode|new sha256|previous sha256（- 表示新增）
readonly -a INSTALLS=(
@@INSTALLS@@
)
readonly PREVIOUS_REQUIRED='@@PREV_REQUIRED@@'
readonly TARGET_REQUIRED='@@TARGET_REQUIRED@@'
readonly PREVIOUS_SOURCE_COUNT=@@PREV_COUNT@@
readonly TARGET_SOURCE_COUNT=@@TARGET_COUNT@@

die() {
  printf 'infrastructure-approval: %s\n' "$1" >&2
  exit "${2:-1}"
}

digest_matches() {
  local path="$1" expected="$2"
  printf '%s  %s\n' "${expected}" "${path}" | sha256sum --check --status
}

secure_root_regular() {
  local path="$1" owner mode
  [[ -f "${path}" && ! -L "${path}" ]] || return 1
  owner="$(stat -c '%U:%G' "${path}")" || return 1
  mode="$(stat -c '%a' "${path}")" || return 1
  [[ "${owner}" == "root:root" && "${mode}" =~ ^[0-7]{3,4}$ ]] || return 1
  (( (8#${mode} & 0022) == 0 ))
}

syntax_ok() {
  local path="$1"
  case "${path}" in
    *.sh) bash -n "${path}" ;;
    *.py) python3 -c 'import sys; compile(open(sys.argv[1], encoding="utf-8").read(), sys.argv[1], "exec")' "${path}" ;;
    *.json) python3 -c 'import json, sys; json.load(open(sys.argv[1], encoding="utf-8"))' "${path}" ;;
    *) return 0 ;;
  esac
}

validate_anchor() {
  # $1 锚文件；$2 期望聚合摘要；$3 期望安装映射 JSON；$4 期望源文件数；$5 pre|post；$6 pre 时跳过的目标（空格分隔）
  python3 - "$1" "$2" "$3" "$4" "$5" "${6:-}" <<'PY'
import hashlib
import json
from pathlib import Path
import re
import stat
import sys


def strict_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate key")
        result[key] = value
    return result


def digest(path):
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


path, expected_aggregate, required_json, count, mode, skip = sys.argv[1:7]
required = json.loads(required_json)
skip = set(skip.split())
metadata = Path(path).lstat()
if (
    Path(path).is_symlink()
    or not stat.S_ISREG(metadata.st_mode)
    or metadata.st_uid != 0
    or metadata.st_gid != 0
    or metadata.st_mode & 0o022
):
    raise SystemExit("infrastructure anchor is unsafe")
payload = json.loads(Path(path).read_text(encoding="utf-8"), object_pairs_hook=strict_object)
if not isinstance(payload, dict) or set(payload) != {
    "schema_version", "infrastructure_sha256", "source_files", "installed_files",
}:
    raise SystemExit("infrastructure anchor shape is invalid")
if payload["schema_version"] != 1:
    raise SystemExit("infrastructure schema is invalid")
sha256 = re.compile(r"^[0-9a-f]{64}$")
source_files = payload["source_files"]
if not isinstance(source_files, dict) or len(source_files) != int(count):
    raise SystemExit("source file set is invalid")
if any(
    not isinstance(name, str)
    or not name.startswith("deploy/cloud/")
    or name == "deploy/cloud/README.md"
    or not isinstance(value, str)
    or sha256.fullmatch(value) is None
    for name, value in source_files.items()
):
    raise SystemExit("source digest is invalid")
canonical = json.dumps(source_files, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
aggregate = hashlib.sha256(canonical).hexdigest()
if aggregate != expected_aggregate or payload["infrastructure_sha256"] != expected_aggregate:
    raise SystemExit("aggregate digest is invalid")
installed_files = payload["installed_files"]
if not isinstance(installed_files, list) or len(installed_files) != len(required):
    raise SystemExit("installed file set is invalid")
installed = {}
for item in installed_files:
    if not isinstance(item, dict) or set(item) != {"source_path", "target_path", "sha256"}:
        raise SystemExit("installed file row is invalid")
    source = item["source_path"]
    if (
        source in installed
        or required.get(source) != item["target_path"]
        or source_files.get(source) != item["sha256"]
    ):
        raise SystemExit("installed file binding is invalid")
    installed[source] = item["target_path"]
if installed != required:
    raise SystemExit("installed target mapping is invalid")
for item in installed_files:
    if mode == "pre" and item["target_path"] in skip:
        continue
    target = Path(item["target_path"])
    metadata = target.lstat()
    if (
        target.is_symlink()
        or not stat.S_ISREG(metadata.st_mode)
        or metadata.st_uid != 0
        or metadata.st_gid != 0
        or metadata.st_mode & 0o022
        or digest(target) != item["sha256"]
    ):
        raise SystemExit(f"installed infrastructure differs: {target}")
PY
}

install_targets() {
  local row
  for row in "${INSTALLS[@]}"; do
    IFS='|' read -r _name target _mode _new _old <<<"${row}"
    printf '%s ' "${target}"
  done
}

restore_previous() {
  local suffix="rollback.${BASHPID}" failed=0 row name target mode new old
  for row in "${INSTALLS[@]}"; do
    IFS='|' read -r name target mode new old <<<"${row}"
    if [[ "${old}" == "-" ]]; then
      rm -f -- "${target}" || failed=1
    elif install -m "${mode}" -o root -g root "${BACKUP}/${name}" "${target}.${suffix}"; then
      mv -Tf "${target}.${suffix}" "${target}" || failed=1
      digest_matches "${target}" "${old}" || failed=1
    else
      failed=1
    fi
  done
  if install -m 0600 -o root -g root "${BACKUP}/release-infrastructure.json" "${ANCHOR_TARGET}.${suffix}"; then
    mv -Tf "${ANCHOR_TARGET}.${suffix}" "${ANCHOR_TARGET}" || failed=1
  else
    failed=1
  fi
  validate_anchor "${ANCHOR_TARGET}" "${PREVIOUS_INFRASTRUCTURE_SHA256}" "${PREVIOUS_REQUIRED}" \
    "${PREVIOUS_SOURCE_COUNT}" "post" || failed=1
  [[ "${failed}" -eq 0 ]]
}

on_error() {
  local rc="${1:-$?}"
  trap - ERR
  trap '' HUP INT TERM
  set +e
  if [[ "${rollback_required:-0}" -eq 1 ]]; then
    if restore_previous; then
      printf 'infrastructure-approval: restored previous files and anchor after failure\n' >&2
      exit "${rc}"
    fi
    printf 'infrastructure-approval: rollback_failed; manual recovery from %s is required\n' "${BACKUP}" >&2
    exit 86
  fi
  exit "${rc}"
}

[[ "${EUID}" -eq 0 ]] || die "must run as root"
[[ -d "${INPUT_ROOT}" && ! -L "${INPUT_ROOT}" ]] || die "root snapshot directory is invalid"
[[ "$(stat -c '%U:%G' "${INPUT_ROOT}")" == "root:root" ]] || die "root snapshot owner is invalid"
[[ "$(stat -c '%a' "${INPUT_ROOT}")" == "700" ]] || die "root snapshot mode is invalid"
for row in "${INSTALLS[@]}"; do
  IFS='|' read -r name target mode new old <<<"${row}"
  secure_root_regular "${INPUT_ROOT}/${name}" || die "root snapshot file is invalid: ${name}"
  digest_matches "${INPUT_ROOT}/${name}" "${new}" || die "staged digest mismatch: ${name}"
  syntax_ok "${INPUT_ROOT}/${name}" || die "staged syntax is invalid: ${name}"
done
secure_root_regular "${INPUT_ROOT}/release-infrastructure.json" || die "staged anchor is invalid"
digest_matches "${INPUT_ROOT}/release-infrastructure.json" "${CANDIDATE_MANIFEST_SHA256}" \
  || die "staged infrastructure manifest digest mismatch"
validate_anchor "${INPUT_ROOT}/release-infrastructure.json" "${TARGET_INFRASTRUCTURE_SHA256}" \
  "${TARGET_REQUIRED}" "${TARGET_SOURCE_COUNT}" "pre" "$(install_targets)"

secure_root_regular "${SCRIPT_ROOT}/transaction-lock.sh" || die "transaction lock helper is unsafe"
digest_matches "${SCRIPT_ROOT}/transaction-lock.sh" "${TRANSACTION_LOCK_SHA256}" \
  || die "transaction lock helper digest mismatch"
source "${SCRIPT_ROOT}/transaction-lock.sh"
lock_rc=0
transaction_lock_acquire "release" || lock_rc=$?
[[ "${lock_rc}" -eq 0 ]] || die "cloud transaction lock is unavailable" "${lock_rc}"

validate_anchor "${ANCHOR_TARGET}" "${PREVIOUS_INFRASTRUCTURE_SHA256}" "${PREVIOUS_REQUIRED}" \
  "${PREVIOUS_SOURCE_COUNT}" "post"
for row in "${INSTALLS[@]}"; do
  IFS='|' read -r name target mode new old <<<"${row}"
  if [[ "${old}" == "-" ]]; then
    [[ ! -e "${target}" && ! -L "${target}" ]] || die "new install target already exists: ${target}"
  else
    digest_matches "${target}" "${old}" || die "installed file changed before approval: ${target}"
  fi
done

[[ ! -e "${BACKUP}" && ! -L "${BACKUP}" ]] || die "infrastructure approval backup already exists"
install -d -m 0700 -o root -g root "${BACKUP}"
for row in "${INSTALLS[@]}"; do
  IFS='|' read -r name target mode new old <<<"${row}"
  [[ "${old}" == "-" ]] && continue
  install -m "${mode}" -o root -g root "${target}" "${BACKUP}/${name}"
  digest_matches "${BACKUP}/${name}" "${old}" || die "backup digest mismatch: ${name}"
done
install -m 0600 -o root -g root "${ANCHOR_TARGET}" "${BACKUP}/release-infrastructure.json"
validate_anchor "${BACKUP}/release-infrastructure.json" "${PREVIOUS_INFRASTRUCTURE_SHA256}" \
  "${PREVIOUS_REQUIRED}" "${PREVIOUS_SOURCE_COUNT}" "post"

rollback_required=1
trap 'on_error $?' ERR
trap 'on_error 129' HUP
trap 'on_error 130' INT
trap 'on_error 143' TERM
for row in "${INSTALLS[@]}"; do
  IFS='|' read -r name target mode new old <<<"${row}"
  install -m "${mode}" -o root -g root "${INPUT_ROOT}/${name}" "${target}.new.${BASHPID}"
  mv -Tf "${target}.new.${BASHPID}" "${target}"
done
install -m 0600 -o root -g root "${INPUT_ROOT}/release-infrastructure.json" "${ANCHOR_TARGET}.new.${BASHPID}"
mv -Tf "${ANCHOR_TARGET}.new.${BASHPID}" "${ANCHOR_TARGET}"

for row in "${INSTALLS[@]}"; do
  IFS='|' read -r name target mode new old <<<"${row}"
  digest_matches "${target}" "${new}"
  syntax_ok "${target}"
done
secure_root_regular "${ANCHOR_TARGET}"
digest_matches "${ANCHOR_TARGET}" "${CANDIDATE_MANIFEST_SHA256}"
validate_anchor "${ANCHOR_TARGET}" "${TARGET_INFRASTRUCTURE_SHA256}" "${TARGET_REQUIRED}" \
  "${TARGET_SOURCE_COUNT}" "post"
rollback_required=0
trap - ERR HUP INT TERM

printf '{"status":"infrastructure_approved","target_sha":"%s","infrastructure_sha256":"%s","backup":"%s"}\n' \
  "${TARGET_SHA}" "${TARGET_INFRASTRUCTURE_SHA256}" "${BACKUP}"
'''

WRAPPER_TEMPLATE = r'''#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

readonly TARGET_SHA="@@TARGET@@"
readonly UPLOAD_ID="@@UPLOAD_ID@@"
readonly STAGE="/opt/car-agent/incoming/releases/${UPLOAD_ID}"
readonly SNAPSHOT="@@SNAPSHOT@@"
readonly APPLY_SHA256="@@APPLY_SHA@@"
readonly MANIFEST_SHA256="@@MANIFEST@@"

die() {
  printf 'infrastructure-snapshot: %s\n' "$1" >&2
  exit "${2:-1}"
}

copy_exact() {
  local source="$1" target="$2" mode="$3" expected="$4" temporary
  [[ -f "${source}" && ! -L "${source}" ]] || die "staged source is invalid"
  temporary="${target}.new.${BASHPID}"
  [[ ! -e "${temporary}" && ! -L "${temporary}" ]] || die "snapshot temporary path exists"
  install -m "${mode}" -o root -g root "${source}" "${temporary}"
  printf '%s  %s\n' "${expected}" "${temporary}" | sha256sum --check --status \
    || die "snapshot digest mismatch"
  mv -Tf "${temporary}" "${target}"
}

syntax_check() {
  case "$1" in
    *.sh) bash -n "$1" ;;
    *.py) python3 -c 'import sys; compile(open(sys.argv[1], encoding="utf-8").read(), sys.argv[1], "exec")' "$1" ;;
    *.json) python3 -c 'import json, sys; json.load(open(sys.argv[1], encoding="utf-8"))' "$1" ;;
  esac
}

[[ "${EUID}" -eq 0 ]] || die "must run as root"
[[ -d "${STAGE}" && ! -L "${STAGE}" ]] || die "staged upload directory is invalid"
[[ -d "${SNAPSHOT}" && ! -L "${SNAPSHOT}" ]] || die "root snapshot directory is invalid"
[[ "$(stat -c '%U:%G' "${SNAPSHOT}")" == "root:root" ]] || die "root snapshot owner is invalid"
[[ "$(stat -c '%a' "${SNAPSHOT}")" == "700" ]] || die "root snapshot mode is invalid"

copy_exact "${STAGE}/apply-infrastructure-approval.sh" \
  "${SNAPSHOT}/apply-infrastructure-approval.sh" 0700 "${APPLY_SHA256}"
copy_exact "${STAGE}/release-infrastructure.json" \
  "${SNAPSHOT}/release-infrastructure.json" 0600 "${MANIFEST_SHA256}"
@@COPIES@@

bash -n "${SNAPSHOT}/apply-infrastructure-approval.sh"
@@CHECKS@@
exec bash "${SNAPSHOT}/apply-infrastructure-approval.sh"
'''

ENTRY_TEMPLATE = r'''#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

readonly TARGET_SHA="@@TARGET@@"
readonly STAGE="@@STAGE@@"
readonly SNAPSHOT_PARENT="/opt/car-agent/shared/evidence/infrastructure-approvals"
readonly SNAPSHOT="@@SNAPSHOT@@"
readonly WRAPPER_SHA256="@@WRAPPER_SHA@@"

die() {
  printf 'infrastructure-entry: %s\n' "$1" >&2
  exit "${2:-1}"
}

main() {
local wrapper_temporary parent_mode
[[ "${EUID}" -eq 0 ]] || die "must run as root"
[[ -d "${STAGE}" && ! -L "${STAGE}" ]] || die "staged upload directory is invalid"
[[ -f "${STAGE}/root-snapshot-wrapper.sh" && ! -L "${STAGE}/root-snapshot-wrapper.sh" ]] \
  || die "staged root wrapper is invalid"

if [[ -e "${SNAPSHOT_PARENT}" || -L "${SNAPSHOT_PARENT}" ]]; then
  [[ -d "${SNAPSHOT_PARENT}" && ! -L "${SNAPSHOT_PARENT}" ]] || die "snapshot parent is invalid"
  [[ "$(stat -c '%U:%G' "${SNAPSHOT_PARENT}")" == "root:root" ]] || die "snapshot parent owner is invalid"
  parent_mode="$(stat -c '%a' "${SNAPSHOT_PARENT}")"
  [[ "${parent_mode}" =~ ^[0-7]{3,4}$ ]] || die "snapshot parent mode is invalid"
  (( (8#${parent_mode} & 0022) == 0 )) || die "snapshot parent is writable"
else
  install -d -m 0700 -o root -g root "${SNAPSHOT_PARENT}"
fi

[[ ! -e "${SNAPSHOT}" && ! -L "${SNAPSHOT}" ]] || die "root snapshot already exists"
install -d -m 0700 -o root -g root "${SNAPSHOT}"
wrapper_temporary="${SNAPSHOT}/root-snapshot-wrapper.sh.new.${BASHPID}"
install -m 0700 -o root -g root "${STAGE}/root-snapshot-wrapper.sh" "${wrapper_temporary}"
printf '%s  %s\n' "${WRAPPER_SHA256}" "${wrapper_temporary}" | sha256sum --check --status \
  || die "root wrapper digest mismatch"
mv -Tf "${wrapper_temporary}" "${SNAPSHOT}/root-snapshot-wrapper.sh"
exec bash "${SNAPSHOT}/root-snapshot-wrapper.sh"
}

main "$@"
'''


def _fill(template: str, values: Mapping[str, str]) -> bytes:
    text = template
    for key, value in values.items():
        text = text.replace(key, value)
    if "@@" in text:
        raise ApprovalError("a root script placeholder was left unfilled")
    return text.encode("utf-8")


@dataclass(frozen=True)
class Materials:
    files: dict[str, bytes]
    summary: dict[str, Any]


def render_materials(
    candidate: Candidate, previous: Mapping[str, Any], previous_bytes: bytes, nonce: str
) -> Materials:
    if not NONCE_RE.fullmatch(nonce):
        raise ApprovalError("upload nonce must be 32 lowercase hex characters")
    sha = candidate.target_sha
    manifest = _sha256(candidate.anchor_bytes)
    upload_id = f"{sha}-{nonce}"
    stage = f"{INCOMING_ROOT}/{upload_id}"
    snapshot = f"{APPROVALS_ROOT}/.candidate-{sha}-{manifest[:8]}"
    backup = f"{APPROVALS_ROOT}/{sha}-{candidate.aggregate[:8]}"
    previous_required = {row["source_path"]: row["target_path"] for row in previous["installed_files"]}
    previous_digest = {row["source_path"]: row["sha256"] for row in previous["installed_files"]}
    apply = _fill(APPLY_TEMPLATE, {
        "@@TARGET@@": sha,
        "@@AGGREGATE@@": candidate.aggregate,
        "@@PREV_AGGREGATE@@": previous["infrastructure_sha256"],
        "@@MANIFEST@@": manifest,
        "@@LOCK_SHA@@": previous_digest[LOCK_HELPER],
        "@@SNAPSHOT@@": snapshot,
        "@@BACKUP@@": backup,
        "@@INSTALLS@@": "\n".join(
            f'  "{item.name}|{item.target}|{item.mode}|{item.new}|{item.old}"' for item in candidate.installs
        ),
        "@@PREV_REQUIRED@@": json.dumps(previous_required, sort_keys=True, separators=(",", ":")),
        "@@TARGET_REQUIRED@@": json.dumps(candidate.required, sort_keys=True, separators=(",", ":")),
        "@@PREV_COUNT@@": str(len(previous["source_files"])),
        "@@TARGET_COUNT@@": str(len(candidate.source_files)),
    })
    wrapper = _fill(WRAPPER_TEMPLATE, {
        "@@TARGET@@": sha,
        "@@UPLOAD_ID@@": upload_id,
        "@@SNAPSHOT@@": snapshot,
        "@@APPLY_SHA@@": _sha256(apply),
        "@@MANIFEST@@": manifest,
        "@@COPIES@@": "\n".join(
            f'copy_exact "${{STAGE}}/{item.name}" "${{SNAPSHOT}}/{item.name}" 0700 "{item.new}"'
            for item in candidate.installs
        ),
        "@@CHECKS@@": "\n".join(f'syntax_check "${{SNAPSHOT}}/{item.name}"' for item in candidate.installs),
    })
    entry = _fill(ENTRY_TEMPLATE, {
        "@@TARGET@@": sha,
        "@@STAGE@@": stage,
        "@@SNAPSHOT@@": snapshot,
        "@@WRAPPER_SHA@@": _sha256(wrapper),
    })
    allowed = {snapshot.rsplit("/", 1)[1], backup.rsplit("/", 1)[1]}
    for script in (apply, wrapper, entry):
        for path in re.findall(r"infrastructure-approvals/([^\"\s]+)", script.decode("utf-8")):
            if path not in allowed:
                raise ApprovalError(f"a root script names an unexpected approval path: {path}")
    files = {APPLY: apply, ANCHOR: candidate.anchor_bytes, WRAPPER: wrapper, ENTRY: entry, **candidate.blobs}
    summary = {
        "target_sha": sha,
        "upload_id": upload_id,
        "stage": stage,
        "snapshot": snapshot,
        "backup": backup,
        "previous_aggregate": previous["infrastructure_sha256"],
        "previous_anchor_sha256": _sha256(previous_bytes),
        "target_aggregate": candidate.aggregate,
        "candidate_manifest_sha256": manifest,
        "source_files": len(candidate.source_files),
        "installed_files": len(candidate.required),
        "changed_sources": list(candidate.changed_sources),
        "installs": [asdict(item) for item in candidate.installs],
        "upload": [APPLY, ANCHOR, WRAPPER, *candidate.blobs],
        "files": {name: _sha256(data) for name, data in sorted(files.items())},
    }
    return Materials(files=files, summary=summary)


# ---------------------------------------------------------------- local checks

_OWNERSHIP_CHECK = (
    "    or metadata.st_uid != 0\n    or metadata.st_gid != 0\n    or metadata.st_mode & 0o022\n"
    "):\n    raise SystemExit(\"infrastructure anchor is unsafe\")"
)


def check_materials(directory: Path, summary: Mapping[str, Any]) -> list[str]:
    """Run the apply script's own anchor validator locally, skipping only the root-ownership check."""
    apply = (directory / APPLY).read_text(encoding="utf-8")
    validator = re.search(r"<<'PY'\n(.*?)\nPY\n", apply, re.S)
    if validator is None or _OWNERSHIP_CHECK not in validator.group(1):
        raise ApprovalError("the anchor validator could not be located in the apply script")
    local = validator.group(1).replace(_OWNERSHIP_CHECK, "):\n    raise SystemExit(\"infrastructure anchor is unsafe\")", 1)
    script = directory / "local-anchor-check.py"
    script.write_text(local, encoding="utf-8")

    def constant(name: str) -> str:
        match = re.search(rf"^readonly {name}=(?:'([^']*)'|\"([^\"]*)\"|(\S+))$", apply, re.M)
        if match is None:
            raise ApprovalError(f"apply script lacks {name}")
        return next(group for group in match.groups() if group is not None)

    targets = " ".join(json.loads(constant("TARGET_REQUIRED")).values())
    previous_targets = " ".join(json.loads(constant("PREVIOUS_REQUIRED")).values())
    cases = [
        ("candidate anchor passes", directory / ANCHOR, constant("TARGET_INFRASTRUCTURE_SHA256"),
         constant("TARGET_REQUIRED"), constant("TARGET_SOURCE_COUNT"), targets, True),
        ("installed anchor passes as the previous one", directory / "previous-anchor.json",
         constant("PREVIOUS_INFRASTRUCTURE_SHA256"), constant("PREVIOUS_REQUIRED"),
         constant("PREVIOUS_SOURCE_COUNT"), previous_targets, True),
        ("candidate anchor fails against the previous aggregate", directory / ANCHOR,
         constant("PREVIOUS_INFRASTRUCTURE_SHA256"), constant("TARGET_REQUIRED"),
         constant("TARGET_SOURCE_COUNT"), targets, False),
    ]
    results = []
    try:
        for label, anchor, aggregate, required, count, skip, should_pass in cases:
            completed = subprocess.run(
                [sys.executable, str(script), str(anchor), aggregate, required, count, "pre", skip],
                capture_output=True, text=True, timeout=60, check=False,
            )
            if (completed.returncode == 0) != should_pass:
                raise ApprovalError(f"local anchor check failed: {label}: {completed.stderr.strip()[-200:]}")
            results.append(label)
    finally:
        script.unlink(missing_ok=True)
    if summary["candidate_manifest_sha256"] != _sha256((directory / ANCHOR).read_bytes()):
        raise ApprovalError("written candidate anchor differs from the rendered one")
    return results


# ---------------------------------------------------------------- steps


def prepare_approval(
    request: ReleaseRequest, runner: CommandRunner, *, nonce: str | None = None
) -> dict[str, Any]:
    target = require_clean_main_commit(request.repo, request.revision)
    directory = request.artifact_root / target
    if directory.exists():
        raise ApprovalError(f"approval materials already exist at {directory}; apply them or move them aside")
    previous_bytes, previous = read_anchor(request, runner)
    candidate = build_candidate(request.repo, target, previous)
    if candidate.aggregate == previous["infrastructure_sha256"]:
        return {"status": "already_approved", "target_sha": target, "target_aggregate": candidate.aggregate}
    materials = render_materials(candidate, previous, previous_bytes, nonce or secrets.token_hex(16))
    directory.mkdir(parents=True)
    for name, data in materials.files.items():
        (directory / name).write_bytes(data)
    (directory / "previous-anchor.json").write_bytes(previous_bytes)
    checks = check_materials(directory, materials.summary)
    summary = {**materials.summary, "local_checks": checks}
    (directory / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return {"status": "prepared", "materials": str(directory), **summary}


def _approved_payloads(stdout: str) -> list[dict[str, Any]]:
    payloads = []
    for line in stdout.splitlines():
        if not line.lstrip().startswith("{"):
            continue
        try:
            payload = json.loads(line)
        except ValueError:
            continue
        if isinstance(payload, dict) and payload.get("status") == "infrastructure_approved":
            payloads.append(payload)
    return payloads


def apply_approval(request: ReleaseRequest, runner: CommandRunner) -> dict[str, Any]:
    target = require_clean_main_commit(request.repo, request.revision)
    directory = request.artifact_root / target
    try:
        summary = json.loads((directory / "summary.json").read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ApprovalError("no prepared approval materials; run without --apply first") from exc
    if (directory / "result.json").exists():
        raise ApprovalError(f"these materials were already applied: {directory / 'result.json'}")
    for name, digest in summary["files"].items():
        try:
            current = _sha256((directory / name).read_bytes())
        except OSError as exc:
            raise ApprovalError(f"approval material is missing: {name}") from exc
        if current != digest:
            raise ApprovalError(f"approval material changed after it was prepared: {name}")

    previous_bytes, _ = read_anchor(request, runner)
    if _sha256(previous_bytes) != summary["previous_anchor_sha256"]:
        raise ApprovalError("the installed anchor changed after these materials were prepared; prepare again")

    ssh = request.ssh
    stage = summary["stage"]
    prepared = runner.run(
        ssh.ssh_argv(
            "sudo /opt/car-agent/shared/bin/remote-release.sh prepare-upload "
            f"--sha {target} --upload-id {summary['upload_id']}"
        ),
        cwd=request.repo, check=False, timeout_s=120,
    )
    if prepared.returncode != 0 or prepared.stdout.strip() != stage:
        raise ApprovalError("prepare-upload did not return the expected upload directory")
    for name in summary["upload"]:
        copied = runner.run(ssh.scp_argv(directory / name, f"{stage}/{name}"), cwd=request.repo, check=False, timeout_s=300)
        if copied.returncode != 0:
            raise ApprovalError(f"could not upload {name}")
    listed = runner.run(
        ssh.ssh_argv(f"cd {stage} && sha256sum -- " + " ".join(summary["upload"])),
        cwd=request.repo, check=False, timeout_s=120,
    )
    remote = {}
    for line in listed.stdout.splitlines():
        fields = line.split()
        if len(fields) == 2:
            remote[fields[1]] = fields[0]
    if listed.returncode != 0 or any(remote.get(name) != summary["files"][name] for name in summary["upload"]):
        raise ApprovalError("staged files do not match the prepared materials")

    with open(directory / ENTRY, "rb") as entry:
        executed = runner.run(
            ssh.ssh_argv("sudo -n bash -s"), cwd=request.repo, stdin=entry, check=False, timeout_s=300
        )
    (directory / "last-run.stderr.txt").write_text(executed.stderr, encoding="utf-8")
    approved = _approved_payloads(executed.stdout)
    if executed.returncode != 0 or len(approved) != 1:
        raise ApprovalError(
            f"the root approval did not report success (exit {executed.returncode}); the apply script restores "
            f"the previous files and anchor on failure; see {directory / 'last-run.stderr.txt'}"
        )
    after_bytes, _ = read_anchor(request, runner)
    if _sha256(after_bytes) != summary["candidate_manifest_sha256"]:
        raise ApprovalError("the installed anchor does not match the approved candidate")
    result = {
        "status": "approved",
        "target_sha": target,
        "target_aggregate": summary["target_aggregate"],
        "previous_aggregate": summary["previous_aggregate"],
        "backup": approved[0].get("backup"),
        "installs": [item["target"] for item in summary["installs"]],
    }
    (directory / "result.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return result
