#!/usr/bin/env python3
"""Generate responses.yaml from Feishu response data."""
import json
import glob
import sys
import os

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(BASE_DIR, 'orchestrator', 'edge', 'knowledge', 'responses.yaml')

# ── Load specific response pages ──
specific_records = []
for f in sorted(glob.glob(os.path.join(BASE_DIR, 'feishu_tblclodUq24mPqnk_*.json'))):
    with open(f, encoding='utf-8') as fh:
        d = json.load(fh)
        specific_records.extend(d['data']['data'])

# Field indices for specific responses:
# 0: 响应 ID  1: 回复语标识  7: 执行状态  11: 回复语 普通话详细  15: 回复语 普通话简洁  22: 执行场景

# ── Load fallback response pages ──
fallback_records = []
for f in sorted(glob.glob(os.path.join(BASE_DIR, 'feishu_tblTlq6fOfrr1M8H_*.json'))):
    with open(f, encoding='utf-8') as fh:
        d = json.load(fh)
        fallback_records.extend(d['data']['data'])

# Field indices for fallback responses:
# 0: 执行场景  1: 回复语 普通话详细 (not used)  2: 普通话-详细  3: 普通话-精简  4: 执行动作  5: 回复语标识


def parse_speech(raw):
    """Split speech text (newline or comma separated) into list, strip whitespace."""
    if not raw or str(raw).strip() == '/':
        return []
    text = str(raw).strip()
    # Split by newline
    parts = [p.strip() for p in text.split('\n') if p.strip()]
    return parts


def parse_status(raw):
    """Parse status field which may be a list or string."""
    if not raw:
        return ''
    if isinstance(raw, list):
        return raw[0] if raw else ''
    return str(raw).strip()


def yaml_str(s):
    """Escape a string for YAML output. Replace newlines with spaces."""
    s = str(s).replace('\n', ' ').replace('\r', '').strip()
    if any(c in s for c in ':#{}[]&*!|>\'@"`'):
        return f'"{s}"'
    return s


def write_response(f, key, scene, status, speech_full, speech_brief):
    """Write a single response entry in YAML."""
    f.write(f'{yaml_str(key)}:\n')
    f.write(f'  scene: {yaml_str(scene)}\n')
    if status:
        f.write(f'  status: {yaml_str(status)}\n')
    f.write(f'  speech_full: {json.dumps(speech_full, ensure_ascii=False)}\n')
    f.write(f'  speech_brief: {json.dumps(speech_brief, ensure_ascii=False)}\n')


# ── Deduplicate: group by 回复语标识, merge branches ──
# Multiple records may share the same 回复语标识 but have different 分支标识
# We want one entry per unique (回复语标识, 执行状态) combination
# Actually, looking at the data, each record has a unique 回复语标识 like open_seat_heating_1
# So we use 回复语标识 as the key directly.

# ── Generate responses.yaml ──
with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('# responses.yaml — 响应话术模板（来源：同行者公版语音指令表 6.1 具体响应表+兜底表）\n')
    f.write('# 按回复语标识组织；每条含 scene/status/speech_full/speech_brief\n')
    f.write('# Auto-generated by scripts/generate_responses.py — DO NOT EDIT MANUALLY\n')

    # ── Specific responses ──
    f.write('\n# ═══════════════════════════════════════════════════\n')
    f.write('# 具体响应\n')
    f.write('# ═══════════════════════════════════════════════════\n')

    seen_keys = set()
    count = 0
    for r in specific_records:
        resp_id = r[0]  # 响应 ID (e.g. R00001)
        key = str(r[1]).strip() if r[1] else ''  # 回复语标识 (e.g. open_seat_heating_1)
        if not key:
            continue
        # Strip any newlines that may have crept into the key
        key = key.replace('\n', '').replace('\r', '').strip()

        status_raw = r[7]   # 执行状态
        status = parse_status(status_raw)

        scene = r[22] if len(r) > 22 and r[22] else ''
        speech_full_raw = r[11]  # 回复语 普通话详细
        speech_brief_raw = r[15] if len(r) > 15 else None  # 回复语 普通话简洁

        speech_full = parse_speech(speech_full_raw)
        speech_brief = parse_speech(speech_brief_raw)

        # Skip entries with no speech at all
        if not speech_full and not speech_brief:
            continue

        # If key already seen, it's a duplicate branch — skip
        # (each 回复语标识 is already unique per branch in the source)
        if key in seen_keys:
            continue
        seen_keys.add(key)

        write_response(f, key, scene, status, speech_full, speech_brief)
        count += 1

    # ── Fallback responses ──
    f.write('\n# ═══════════════════════════════════════════════════\n')
    f.write('# 通用兜底反馈语\n')
    f.write('# ═══════════════════════════════════════════════════\n')

    for r in fallback_records:
        scene = r[0]       # 执行场景
        key = r[5]         # 回复语标识
        speech_full_raw = r[2]  # 普通话-详细
        speech_brief_raw = r[3]  # 普通话-精简

        if not key:
            continue

        speech_full = parse_speech(speech_full_raw)
        speech_brief = parse_speech(speech_brief_raw)

        # Skip entries with no speech (like Car_general_restrictions_12, 13)
        if not speech_full and not speech_brief:
            continue

        # Determine status based on key pattern
        if 'restrictions' in key:
            status = '安全限制'
        elif 'restricted' in key or 'permission' in key:
            status = '安全限制'
        elif 'need' in key or 'log_in' in key:
            status = '需登录'
        elif 'no_resource' in key or 'no_source' in key:
            status = '异常'
        elif 'bluetooth' in key:
            status = '异常'
        elif 'favorite' in key:
            status = '异常'
        else:
            status = '异常'

        write_response(f, key, scene, status, speech_full, speech_brief)

    # ── Preserved safety fallback responses (from existing responses.yaml) ──
    f.write('\n# ═══════════════════════════════════════════════════\n')
    f.write('# 通用兜底（保留原有）\n')
    f.write('# ═══════════════════════════════════════════════════\n')

    # generic_success
    write_response(f, 'generic_success', '操作成功', '成功',
                   ['已为您完成操作'], ['好的'])

    # generic_fail
    write_response(f, 'generic_fail', '操作失败', '失败',
                   ['抱歉，该操作暂时无法完成'], ['操作失败了'])

    # unsupported_command
    write_response(f, 'unsupported_command', '不支持的指令', '不支持',
                   ['暂不支持该控制指令'], ['暂不支持哦'])

    # model_not_supported
    write_response(f, 'model_not_supported', '当前车型不支持', '不支持',
                   ['当前车型不支持该功能'], ['当前车型不支持哦'])

print(f'Generated {OUTPUT}')
print(f'Total specific response records: {len(specific_records)}')
print(f'Total fallback response records: {len(fallback_records)}')
print(f'Specific responses written: {count}')
